#name: GitHub Actions Demo
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
#on: [push]
#jobs:
#  init:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [ 18.x ]
#    steps:
  name: GitHub Actions Demo
  run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
  on: [ push ]
  jobs:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
